### Config ###
global:
  account_prefix: tiplike-
  abe_url: http://api.monaco-ex.org/abe/
coin:
  name: Likecoin
  unit: LIKE
  address_prefix: L
twitter:
  tipbot:
    screen_name: tiplike
    userid: 2762501305
  faucet:
    userid: 2762538295
  maintainer:
    userid: 2611149793
    screenname: MonacoEx
  developer:
    userid: 2611149793
