### Config ###
global:
  account_prefix: tipyaythorowrin-
  abe_url: http://api.monaco-ex.org/abe/
coin:
  name: Yaycoin
  unit: YAY
  address_prefix: Y
twitter:
  tipbot:
    screen_name: tipyay
    userid: 2762505847
  faucet:
    userid: 2762468190
  maintainer:
    userid: 2611149793
    screenname: MonacoEx
  developer:
    userid: 2611149793
